#!/bin/sh
PREREQ="udev"
prereqs() { echo "$PREREQ"; }
case $1 in prereqs) prereqs; exit 0 ;; esac

if [ -x /usr/sbin/pcscd ]; then
    mkdir -p /run/pcscd;
    /usr/sbin/pcscd --info --color;

    sleep 2;
fi

