pam_pkcs11 {
	debug = false;
	nullok = true;
	use_pkcs11_module = opensc;

	pkcs11_module opensc {
		module = /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so;
		description = "OpenSC PKCS#11 module";
		slot_num = 0;
		support_threads = false;
		cert_policy = none;
	}

	use_mappers = cn, null, getpwent;

	mapper null {
		default_match = true;
		default_user = efortmeyer;
	}
}

