pam_pkcs11 {
	nullok = true;
	debug = false;
	use_pkcs11_module = opensc;

	pkcs11_module opensc {
		module = /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so;
		description = "OpenSC PKCS#11 module";
		slot_num = 0;
		support_threads = false;
		cert_policy = none;
	}

	use_mappers = subject;

	mapper subject {
		debug = true;
		module = internal;
		ignorecase = true;
		mapfile = file:///etc/pam_pkcs11/subject_mapping;
	}
}

