#!/bin/sh

set -e

PREREQ=""

prereqs() { 
	echo "$PREREQ"; 
}

case "$1" in 
	prereqs) 
		prereqs; 
		exit 0 
		;; 
esac

. /usr/share/initramfs-tools/hook-functions

if [ -x /usr/sbin/pcscd ]; then
	copy_exec /usr/sbin/pcscd
fi

# copy binaries and dynamic links to initramfs
find /usr/lib/x86_64-linux-gnu -maxdepth 1 \
    \(\
		-name "libpcsclite*.so*" -o \
		-name "libusb*" -o \
		-name "libgcc_s.so*" -o \
		-name "*pkcs11*" -o \
		-name "*opensc*" -o \
		-name "*p11*" \
	\) \
    -exec sh -c '. /usr/share/initramfs-tools/hook-functions; copy_exec "$1"' sh {} \;
find /usr/lib/x86_64-linux-gnu/pkcs11 -name "*.so" -exec sh -c '. /usr/share/initramfs-tools/hook-functions; copy_exec "$1"' sh {} \; 2>/dev/null
find /usr/lib/x86_64-linux-gnu/cryptsetup -name "*.so" -exec sh -c '. /usr/share/initramfs-tools/hook-functions; copy_exec "$1"' sh {} \; 2>/dev/null
find /usr/lib/pcsc -name "*.so" -exec sh -c '. /usr/share/initramfs-tools/hook-functions; copy_exec "$1"' sh {} \; 2>/dev/null

# copy text files to initramfs
find /usr/lib/pcsc -name "*.plist" -exec sh -c '. /usr/share/initramfs-tools/hook-functions; copy_file plist "$1"' sh {} \; 2>/dev/null
find /usr/share/p11-kit -name "*.module" -exec sh -c '. /usr/share/initramfs-tools/hook-functions; copy_file module "$1"' sh {} \; 2>/dev/null