#!/bin/sh
PREREQ=""
prereqs() { echo "$PREREQ"; }
case $1 in prereqs) prereqs; exit 0 ;; esac
. /usr/share/initramfs-tools/hook-functions

if [ -x /usr/sbin/pcscd ]; then
	copy_exec /usr/sbin/pcscd
fi

if [ -f /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so ]; then
	copy_exec /usr/lib/x86_64-linux-gnu/opensc-pkcs11.so
fi

for pcslitedep in /usr/lib/x86_64-linux-gnu/libpcsclite.so*; do
	copy_exec $pcslitedep
done

if [ -d  /usr/share/p11-kit ]; then
	mkdir -p ${DESTDIR}/usr/share/p11-kit
	cp -a /usr/share/p11-kit/* ${DESTDIR}/usr/share/p11-kit/
fi

for usbdep in /usr/lib/x86_64-linux-gnu/libusb*; do
	copy_exec $usbdep
done

for p11dep in /usr/lib/x86_64-linux-gnu/*p11*; do
	copy_exec $p11dep
done

for pkcs11dep in /usr/lib/x86_64-linux-gnu/pkcs11/*; do
	copy_exec $pkcs11dep
done

if [ -f /usr/lib/x86_64-linux-gnu/pkcs11-spy.so ]; then
	copy_exec /usr/lib/x86_64-linux-gnu/pkcs11-spy.so
fi

for openscdep in /usr/lib/x86_64-linux-gnu/*opensc*; do
	copy_exec $openscdep
done

if [ -d /usr/lib/pcsc ]; then
	mkdir -p ${DESTDIR}/usr/lib/pcsc
	cp -a /usr/lib/pcsc/* ${DESTDIR}/usr/lib/pcsc/

	for driver in $(find /usr/lib/pcsc -name "*.so"); do
		copy_exec "$driver"
	done	
fi

if [ -f /etc/libccid_Info.plist ]; then
	mkdir -p ${DESTDIR}/etc
	cp -p /etc/libccid_Info.plist ${DESTDIR}/etc
fi

for plugin in /usr/lib/x86_64-linux-gnu/cryptsetup/*.so; do
	if [ -f "$plugin" ]; then
		copy_exec "$plugin"
	fi
done
